### ISSUE TITLE
decide how to handle beacons with no data

### ISSUE THREAD

**Issue by fergald** [WICG/pending-beacon#17]
What should happen to a POST-beacon if `setData` has never been called (or has been called with `null`)?

It seems reasonable to be able to set up beacons that are expecting data but do nothing if the document is destroyed before that data is set.

A POST beacon can be constructed without data, can a GET beacon can be constructed without a URL?

@philipwalton

**Comment by philipwalton** [comment]
> What should happen to a POST-beacon if setData has never been called (or has been called with null)?

I could imaging an analytics system where the lack of body data is intended to indicate that X never happened. Though I suppose you could just as easily implement that via default data that gets overridden once X happens.

Calling `setData()` with null (or even an empty string) seems a bit weird, but I suppose could be the same as above (e.g. the user did X but then pressed UNDO or something).

> can a GET beacon can be constructed without a URL?

Hard to say. My initial sense is that should be an error.  Alternatively you could just not send anything.

I'm not sure there's a use case for creating a beacon and then setting the URL conditionally based on what the user does.

**Comment by fergald** [comment]
> I'm not sure there's a use case for creating a beacon and then setting the URL conditionally based on what the user does.

It's a convenience. Imagine a value that shouldn't be sent until something happens but can also be updated. You could do

```js
let beacon;
function recordValue(value) {
  const url = makeUrl(value);
  if (!beacon) {
    beacon = new GetBeacon(url)
  } else {
    beacon.setUrl(url)
  }
}
```

it would be nicer to do

```js
let beacon new GetBeacon(null);
function recordValue(value) {
  beacon.setUrl(makeUrl(value));
}
```

**Comment by philipwalton** [comment]
Sure, I could see that being potentially useful.

I could also see an argument for supporting that to be consistent with supporting POST beacons with no body.

**Comment by fergald** [comment]
So maybe a POST beacon with `null`/`undefined` data does not send. If someone wants to send a POST with no body, they can `setData('')`.

That would give us full consistency, I think.

**Comment by philipwalton** [comment]
Yeah, explicitly setting an empty string make it pretty clear what behavior you want, whereas not setting anything could have just been a mistake.

**Comment by mingyc** [comment]
Current spec says `url` is not optional when constructing a beacon. I think calling it with `null`/`undefined` should still be the same.

I will update the explainer mentioning this & `setData('')` for POST beacon.

**Comment by mingyc** [comment]
@fergald @philipwalton I need more input before implementing this.

In my [previous PR][1], @philipwalton suggests that the following usage still works for `navigator.sendBeacon()` and should not throw exception

```js
// Sends to `/undefined`
navigator.sendBeacon(undefined)

// Sends to `/null`
navigator.sendBeacon(null)
```

Also I found that sending with no data also works, as `data` is optional by default for `sendBeacon()`.

So the suggestion here to use null/undefined as signals to tell if a beacon is ready to send actually makes the two APIs inconsistent.



[1]: https://github.com/WICG/unload-beacon/pull/19#discussion_r937219463

**Comment by clelland** [comment]
I think that `undefined` and `null` are unfortunately serializing into those strings, and being used as a relative URL. It's probably a side effect of JS bindings forcing those values into a USVString.

An empty URL should also be valid, and would probably resolve to the document's base URL. (That might be weird for GET beacons, since it would usually just end up fetching the document again, but technically valid)

**Comment by mingyc** [comment]
Trying to summarize the discussion so far.

This issue is to request to use a default state to distinguish whether a post/get pending beacon is ready to send. The discussion in https://github.com/WICG/unload-beacon/issues/17#issuecomment-1198871880 and above suggests to use `undefined` or `null` as the default states.

However, if we want to make `Pending*Beacon` behave consistent with `navigator.sendBeacon()`, we need to consider the latter's usage of `undefined`/`null`. It turns out that the latter can still send out when url=undefined/null (mentioned in https://github.com/WICG/unload-beacon/issues/17#issuecomment-1226811420)

I think there are two options:

1. Only put the constraint on `PendingPostBeacon` that it must have `setData()` called with non-undefined & non-null value, as `data` is by default undefined and cannot be set in ctor. 
   - For `PendingGetBeacon` (or `PendingPostBeacon`), no matter what its `url` is, they can be sent out by browser.
   - Users calling `sendNow()` should also work when url is undefined/null, but not work when data is empty. This is basically consistent with the proposed constraint on browser sending.

2. In addition to `1`, also put the constraint that a beacon must have a non-undefined and non-null `url` to be sent by browser.
   - But users can still call `sendNow()` to force sending out a beacon with null/undefined url (to match `navigator.sendBeacon()`'s existing behavior).
   - However, this option introduces inconsistency between `sendNow()` and the browser's internal send action on timeout/bfcache eviction.

WDYT?

**Comment by clelland** [comment]
We could also fix `navigator.sendBeacon()` to throw an error if passed `undefined`/`null` as a URL; I suspect that if we looked into it, there would be practically no intentional uses of that behaviour in the wild.
