### ISSUE TITLE
Scoping confusion

### ISSUE THREAD

**Issue by annevk** [WICG/pending-beacon#64]
Early in the document you say it's scoped to a document, but then elsewhere you do

> Insert beacon into the user agent’s pending beacon set.

**Comment by mingyc** [comment]
Could you point me where this quote come frome? I couldn't find it in the latest explainer.

I suspect that it's about implementation detail (that browser maintains a set of pending beacons so that it won't be deleted when document is gone)

**Comment by mingyc** [comment]
Could you point me where this quote come frome? I couldn't find it in the latest explainer.

I suspect that it's about implementation detail (that browser maintains a set of pending beacons so that it won't be deleted when document is gone)

**Comment by mingyc** [comment]
Spec is outdated compared to latest explainer.

Note: quote is from https://wicg.github.io/pending-beacon/#pendingbeacon-interface

**Comment by clelland** [comment]
I originally wrote that as I expected that, while the beacon data is associated with a specific document, it needs to be owned by the UA so that it can continue to exist (and be sent) when the document is destroyed. So the conceptual model is that the UA has set of beacons, and knows what documents each is associated with, and decides when to send them.

**Comment by annevk** [comment]
How can it know about the document if the document is destroyed? That doesn't quite add up. You'd need to associate a bunch of state explicitly with it.
